package Radium.Scripting;

public enum NodeType {

    Start,
    Update,
    GetComponent,
    Integer,
    Float,
    Boolean,
    Texture,
    Color,
    Add,
    Subtract,
    Multiply,
    Divide,
    Sine,
    Cosine,
    Normalize,
    Vector3Add,
    Vector3Subtract,
    Vector3Multiply,
    Vector3Divide,
    Vector3Lerp,
    Vector3ToColor,
    ColorToVector3,
    DecomposeVector,
    ComposeVector,
    Log,
    Time,
    Position,
    SetPosition,
    Rotation,
    SetRotation,
    Scale,
    SetScale,
    Translate,
    Rotate,
    Scaling,
    DestroyMesh,
    SetMaterialTexture,
    SetMaterialNormalMap,
    SetMaterialSpecularMap,
    ToggleNormalMap,
    ToggleSpecularMap,
    ToggleSpecularLighting,
    ToggleCullFaces,
    SetOutlineWidth,
    SetOutlineColor,

}
